{
 "title": "dashboard2",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "nic",
    "query": {
     "query": "label_values(node_network_info{instance=\"$instance\"}, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\", device=~\"$nic\"}[5m])",
     "legendFormat": "{{ device }} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\", device=~\"$nic\"}[5m]) * -1",
     "legendFormat": "{{ device }} - Transmit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\"}[1m])) without (cpu)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"$instance\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total\n{instance=\"$instance\", mode=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"$instance\"} / node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Load Average [1m]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$instance\"}",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$instance\"}",
     "legendFormat": "{{ sysname }} {{ release }}"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   ]
  }
 ]
}